//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amozeshgah.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CoTable()
        {
            this.selectCourses = new HashSet<selectCourse>();
        }
    
        public string coid { get; set; }
        public string teacherId { get; set; }
        public Nullable<int> dptID { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> capacity { get; set; }
        public Nullable<int> hour { get; set; }
        public string start_date { get; set; }
        public string classId { get; set; }
        public string logo { get; set; }
    
        public virtual classTable classTable { get; set; }
        public virtual DeptTable DeptTable { get; set; }
        public virtual teacherTable teacherTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<selectCourse> selectCourses { get; set; }
    }
}
