//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amozeshgah.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NetCollegeEntities : DbContext
    {
        public NetCollegeEntities()
            : base("name=NetCollegeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<classTable> classTables { get; set; }
        public virtual DbSet<CoTable> CoTables { get; set; }
        public virtual DbSet<DeptTable> DeptTables { get; set; }
        public virtual DbSet<selectCourse> selectCourses { get; set; }
        public virtual DbSet<stTable> stTables { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<teacherTable> teacherTables { get; set; }
        public virtual DbSet<usersTable> usersTables { get; set; }
    }
}
