//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amozeshgah.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class selectCourse
    {
        public int rowID { get; set; }
        public string stid { get; set; }
        public string coid { get; set; }
        public Nullable<double> grade { get; set; }
        public string description { get; set; }
        public string pardakht { get; set; }
    
        public virtual CoTable CoTable { get; set; }
        public virtual stTable stTable { get; set; }
    }
}
