//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amozeshgah.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class teacherTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public teacherTable()
        {
            this.CoTables = new HashSet<CoTable>();
        }
    
        public string teacherId { get; set; }
        public string teacherName { get; set; }
        public string teacherFamily { get; set; }
        public string teacherAddress { get; set; }
        public string teacherTel { get; set; }
        public string TeacherCetifacrte { get; set; }
        public string TeacherExpert { get; set; }
        public string teImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoTable> CoTables { get; set; }
    }
}
