//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amozeshgah.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class usersTable
    {
        public string username { get; set; }
        public string password { get; set; }
        public string uname { get; set; }
        public string ufamily { get; set; }
        public Nullable<int> accessType { get; set; }
    }
}
